### ISSUE TITLE
Download-Link funktioniert nicht

### ISSUE THREAD

**Issue by Keck72** [iNaD/download-station-ardmediathek#3]
Hallo,

ich habe versucht aus der ARD-Mediathek die letzte Folge des Großstadtreviers mit der Synology DS214play herunterzuladen. Leider funktioniert der Link http://mediathek.daserste.de/Gro%C3%9Fstadtrevier/Folge-305-Hamburg-Paris-und-zur%C3%BCck/Das-Erste/Video?documentId=27661908&topRessort=tv&bcastId=3001570 nicht. Auch wenn ich die Sonderzeichen ß und ü in dem Link manuell einfüge läuft es nicht. Ist bei bei der ARD schon öfter passiert, dass ein Link nicht funktioniert hat. Bei allen anderen Sendern läuft das Tool sonst aber sehr gut und ist wirklich hilfreich. Vieen Dank für die Arbeit und ich hoffe, das Problem bei der ARD Mediathek lässt sich auch leicht lösen.

Schöne Grüße
Kai

**Comment by iNaD** [comment]
Hallo Kai,

entschuldige die verspätete Antwort. Ich werde mir den Link gerade mal anschauen, bin bis jetzt noch nicht dazu gekommen.

**Comment by iNaD** [comment]
So und schon das Problem bzw. die Lösung gefunden :)

Es gibt sowohl ardmediathek.de als auch mediathek.daserste.de. Zweiteres war mir und dem Hosting Provider nicht bekannt und wurde somit nicht als ARD Mediathek Link identifiziert.
Ich werde gleich die Version 0.5 veröffentlichen, diese sollte dein Problem dann beheben.

Ich bitte dich dann um Feedback.

Nächtliche Grüße,
Daniel

**Comment by Keck72** [comment]
Moin Daniel,
vielen lieben Dank für die schnelle Hilfe. Jetzt startet der Download sofort.
Mir ist das auch nicht aufgefallen, dass es sowohl ardmediathek.de als auch mediathek.daserste.de gibt und die Sendungen über beide Seiten abrufbar sind. ich habe die Seite immer manuel eingegeben und bin dann wohl unbewusst mal auf ard.de und mal auf daserste.de gegangen. Bei letzterer schlug der Downloadversuch dann aber wohl immer fehl, ich habs aber nicht realisiert. Schön, dass Du das Problem so schnell lösen konntest. Mein Sohn wird sich freuen, wenn ich ihm dann heute noch die verpasste Folge präsentieren kann ;-)

Schönes Wochenende
wünscht
Kai
