### ISSUE TITLE
Download startet nicht

### ISSUE THREAD

**Issue by midre** [iNaD/download-station-ardmediathek#4]
Hallo,

zunächst: Vielen Dank für die Entwicklung dieses Tools. Danach habe ich gesucht!

Ich teste gerade Synology Download Station Mediathek Hosting Provider für ARD und ZDF. Ich habe ardmediathek.host 0.6b und zdfmedithek.host 0.4b unter Dateihosting in Dowloadstation der Synology eingefügt. Ich kann die URL hinzufügen. Die Downloads erscheinen in der Liste, aber sie starten nicht.Meine DSM-Version ist 5.2-5644 Update 3.

Könne Sie mir mit dme Problem weiterhelfen?

Herzliche Grüße aus Marburg

Micha Dreyer

**Comment by iNaD** [comment]
Hallo Micha,

könntest du bitte mir die URLs mitteilen und ggf. einen Screenshot von der Download Station machen?
Dann kann ich besser analysieren wo das Problem liegt und in welchem Zustand die DS hängen bleibt.

Grüße,
Daniel

**Comment by midre** [comment]
Hallo Daniel,

hier zwei Beispiele für URL:
http://www.zdf.de/ZDFmediathek#/beitrag/video/2621946/Die-Pfeiler-der-Macht-%281%29
http://www.ardmediathek.de/tv/Tagesschau/tagesschau-08-00-Uhr/Das-Erste/Video?documentId=33001394&bcastId=4326

[image: Inline-Bild 1]

Herzliche Grüße

Micha

Am 27. Januar 2016 um 11:06 schrieb Daniel Gehn <notifications@github.com>:

**Comment by iNaD** [comment]
Hi Micha,

das ist wirklich eigenartig. Bei mir funktioniert es. Das Bild hat GitHub aus der E-Mail leider nicht übernommen. Vielleicht könntest du das über die Webseite von Github nochmal hochladen (Unten am Textfeld steht `Attach files by dragging & dropping,  Dateien auswählen selecting them, or pasting from the clipboard.`. Da entweder reinziehen oder auf `selecting them` und dann auswählen ;)

Der ZDF Provider hat übrigens vorhin ein Update erhalten (welches allerdings keine Auswirkungen auf diese Links haben sollte).

Grüße,
Daniel

**Comment by midre** [comment]
Hallo Daniel,

es tut mir Leid: Du hattest leider Kontakt zu einem DAU
<https://de.wikipedia.org/wiki/D%C3%BCmmster_anzunehmender_User>.
Weil ich hatte mir vor längerem schon ein Profil angelegt, dass die
Diskstation nur nachts ruterladen soll (damit Tagsüber das DSL nicht
unnötig belastet wird). Heute Nacht hat die Diskstaion ganz brav die
Dateien runtergeladen...

Vielen Dank nochmal für Deine Mühe und Programmierarbeit!

Herzliche Grüße

Micha

Am 27. Januar 2016 um 22:46 schrieb Daniel Gehn <notifications@github.com>:

**Comment by iNaD** [comment]
Das erklärt natürlich so einiges ;)
