### ISSUE TITLE
ARD-Mediathek-Download scheitert

### ISSUE THREAD

**Issue by HJMeyer** [iNaD/download-station-ardmediathek#5]
Bei Eingabe von:
http://www.daserste.de/unterhaltung/film/filme-im-ersten/videos/der-zuerich-krimi-borcherts-abrechnung-102.html  (Der Zürich-Krimi: Borcherts Abrechnung 05.05.16 | 88:37 Min.)
wird bei mir nur der Html-Text der Seite heruntergeladen. 

Bisher lief es gut. Habe die neuste Version v0.6b (15.05.2015 22:34) der Datei ardmediathek.host 
installiert, leider ohne Erfolg beim Herunterladen des o.g. Films.

Meine DS: DS216play, DSM 6.0-7321 Update 6

Mache ich etwas falsch? Oder woran liegt es?

Danke und Gruß, HJ-Meyer

**Comment by HJMeyer** [comment]
Habe leider die anderen Kommentare erst nach meinem obigen Kommentar zu Gesicht bekommen. Die Lösung war, dass ich die falsche Adresse für das Video genommen habe. Offenbar verwendet die ARD mehrere Adressen, über die man den Film ansehen kann. Bei http://mediathek.daserste.de/Filme-im-Ersten/Der-Z%C3%BCrich-Krimi-Borcherts-Abrechnung/Das-Erste/Video?documentId=35154402&topRessort&bcastId=1933898 beginnt der Download der mp4-Datei sofort.

Danke und Gruß, HJ-Meyer

**Comment by iNaD** [comment]
Hi,

schön dass du eine Lösung finden konntest. Vielleicht finde ich demnächst mal Zeit, um weitere Link Arten hinzuzufügen.

**Comment by ways2web** [comment]
es gehen halt nur die Links aus der Mediathek, nicht die von der normalen ARD Seite.

**Comment by iNaD** [comment]
Das Problem kann hier weiter verfolgt werden: https://github.com/iNaD/ds-mediatheken/issues/3
